export const projects = [
  { name: "Caucasync", url: "https://caucasync.com/en" },
  { name: "Parfume", url: "https://parfumedeparis.az/az" },
  { name: "Galeon", url: "https://galeon.az/az" },
  { name: "Barshop", url: "https://barshop-clone.vercel.app/" },
  { name: "ePROMO", url: "https://epromo.az" },
  { name: "1sigorta.az", url: "https://1sigorta.az/" },
  { name: "Baharatci", url: "https://baharatci-clone.vercel.app/" },
  { name: "GN Traffic", url: "https://v2.gntraffic.dev" },
  { name: "Cosmopark", url: "https://cosmo-parkme.vercel.app/" },
  { name: "Workr", url: "https://yusifsworkr.vercel.app/" },
  { name: "Mi'esta", url: "https://method.kon.az/" },
  { name: "Action", url: null },
  { name: "Azer Tech", url: "https://azer-tech-clone.vercel.app/" },
  { name: "SS System", url: "https://www.smartsistem.az/" },
  { name: "Berber.Shop", url: "https://berbershop.az/" },
];
